### ISSUE TITLE
svyfgt example matchin stata results

### ISSUE THREAD

**Issue by DjalmaPessoa** [guilhermejacob/context#13] opened 2016-12-23 14:25 UTC
I believe I finaly understood the example.
It seems that Stata doesn't have a method for computing the rate of poor people when the poverty line is estimated like: 0.6 * q.50. So we only can compare with results from svyfgt  when type_thresh='abs'.

Wouldn't be possible a threshold= 1000 in Stata.?  
I believe it is rather confusing to work with 0.6* quantile()
This completly different from using svyfgt with:
 type_thresh='relq' ,which would be the correct thing to do. So,  I suggest you include a note explaining that.  Perhaps we should also include the result we think is correct computing with svyfgt and type_thresh='relq'.

What Stata is doing is: 
 svymean(~I((eybhc0<unwtd_arpt81)*1),subset( z , year == 1981 ))
 for this, we don't even need to use convey.

**Comment by ajdamico** [comment] 2016-12-23 14:50
duplicate of https://github.com/DjalmaPessoa/convey/issues/196

**Closed as completed by ajdamico** 2016-12-23 14:50 UTC
