### ISSUE TITLE
svyfgt examples

### ISSUE THREAD

**Issue by DjalmaPessoa** [guilhermejacob/context#14] opened 2016-12-26 11:45 UTC
To me it is ok to keep the example that is there if we improve the Note before the example. 
It should be explained that when the poverty threshold is estimated from the sample, svyfgt should be used with type_thresh="relm"or "relm". In this example it was used type_thresh="abs" just for the sake of comparing results.

**Comment by ajdamico** [comment] 2016-12-26 12:14
could you make whatever improvements you recommend?  thanks

**Comment by ajdamico** [comment] 2016-12-26 14:03
duplicate of https://github.com/DjalmaPessoa/convey/issues/196

**Closed as completed by ajdamico** 2016-12-26 14:03 UTC
